name: CI/CD Pipeline

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main

env:
  TRAIN_FILE: "MLproject/X_train.csv"
  TEST_FILE: "MLproject/X_test.csv"
  YTRAIN_FILE: "MLproject/y_train.csv"
  YTEST_FILE: "MLproject/y_test.csv"

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true   # supaya file dataset LFS ikut di-pull

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "TRAIN_FILE=$TRAIN_FILE"
          echo "TEST_FILE=$TEST_FILE"
          echo "YTRAIN_FILE=$YTRAIN_FILE"
          echo "YTEST_FILE=$YTEST_FILE"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0

      - name: Run MLflow Project
        run: |
          mlflow run MLproject --env-manager=local \
            -P X_train=$TRAIN_FILE \
            -P X_test=$TEST_FILE \
            -P y_train=$YTRAIN_FILE \
            -P y_test=$YTEST_FILE

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "dc"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diabetes-classifier:latest
